// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyOnlineShop.Models;

public partial class Customer
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Street { get; set; }

    public string Zip { get; set; }

    public string Place { get; set; }

    public int? IdCt { get; set; }

    public string Username { get; set; }

    public string PwHash { get; set; }

    public DateTime? UserCreated { get; set; }

    public bool? IsAdmin { get; set; }
}