// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyOnlineShop.Models;

public partial class Deal
{
    public int Id { get; set; }

    public double? Total { get; set; }

    public DateTime? LastUpdate { get; set; }

    public bool? Done { get; set; }
}