// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyOnlineShop.Models;

public partial class Item
{
    public int Id { get; set; }

    public string Name { get; set; }

    public double? Price { get; set; }

    public string Description { get; set; }

    public int? IdIc { get; set; }

    public string Filename { get; set; }

    public string Filepath { get; set; }
}