// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyOnlineShop.Models;

public partial class ShoppingCart
{
    public int Id { get; set; }

    public double? Price { get; set; }

    public DateTime? DateAdded { get; set; }

    public int? IdDl { get; set; }

    public int? IdCs { get; set; }

    public int? IdIt { get; set; }
}